config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
root 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  validates_uniqueness_of :pet_id, scope: :user_id
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable 
  has_many :likes, dependent: :destroy
  has_many :liked_pets, through: :likes, source: :pet
  has_many :pets
  has_many :comments, dependent: :destroy
  def already_liked?(pet)
    self.likes.exists?(pet_id: pet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    pet = Pet.find(params[:pet_id])
    comment = pet.comments.build(comment_params)
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(pet_id: params[:pet_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(pet_id: params[:pet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def new
        @pet= Pet.new
      end
      def index
        if params[:search] == nil
          @pets= Pet.all
        elsif params[:search] == ''
          @pets= Pet.all
        else
          #部分検索
          @pets = Pet.where("genre LIKE ? ",'%' + params[:search] + '%')
        end 
        
     end
      def create
        pet = Pet.new(pet_params)
        pet.user_id = current_user.id
        if pet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @pet = Pet.find(params[:id])
        @comments = @pet.comments
        @comment = Comment.new
    end
    
      private
      def pet_params
        params.require(:pet).permit(:name, :genre, :kind, :age, :detail, :image)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inuneko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4d06a3c401.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <h1>GeekTwitter</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/index.html.erb
<h1>動物</h1>
<h3>一覧ページ</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"pets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= link_to "新規投稿へ", new_pet_path %>
<div class="pets-container">
  <% @pets.each do |t| %>
    <div class="pet">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.genre %>
      <%= t.kind %>
      <%= t.age %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to pet_like_path(id: t.id, pet_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to pet_likes_path(id: t.id, pet_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<h1>動物</h1>
<h3>新規投稿ページ</h3>
<%= form_for @pet do |f| %>

# データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :petname %>
    <%= f.text_field :name, :size => 30 %>
  </div>

# データ型がstringで自由記述の入力フォーム
<div class="field">
<%= f.label :petgenre %>
<%= f.text_field :genre, :size => 30 %>
</div>

# データ型がstringで自由記述の入力フォーム
<div class="field">
<%= f.label :petkind %>
<%= f.text_field :kind, :size => 30 %>
</div>


# データ型がintegerで数字のみを入力するフォーム
  <div class="field">
    <%= f.label :petage  %>
    <%= f.number_field :age, :size => 10 %>
  </div>

# データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :problem  %>
    <%= f.text_area :detail, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
 

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", pets_path %>

app/views/pets/show.html.erb
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@pet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>